stages:
  - build
  - deploy

build_solution:
  stage: build
  only:
    - beta
    - main
  script:
    - "npm i"
    - "npm run build"
  artifacts:
    expire_in: 1 week
    paths:
      - build

deploy_beta:
  stage: deploy
  only:
    - beta
  script:
    - "cp ./build/* C:/daroog/tabadol/beta-front/ -force -recurse"
  environment:
    name: staging
    url: http://beta.daroog.org
    
deploy_daroog:
  stage: deploy
  only:
    - main
  script:
    - "cp ./build/* C:/daroog/tabadol/front/ -force -recurse"
  environment:
    name: staging
    url: http://tabadol.daroog.org
