export enum ExchangeStatesEnum {
  UNKNOWN = 0,
  NOSEND = 1,
  WAITFORB = 2,
  CONFIRMB_AND_WAITFORA = 3,
  CONFIRMA_AND_B = 4,
  NOCONFIRMB = 5,
  CONFIRMB_AND_NOCONFIRMA = 6,
  CANCELLED = 7,
  CONFIRMA_AND_B_PAYMENTA = 8,
  CONFIRMA_AND_B_PAYMENTB = 9,
  CONFIRMALL_AND_PAYMENTALL = 10
}

export enum CancellerEnum {
  PHARMACYA_NOTRESPONSE = 1,
  PHARMACYB_NOTRESPONSE = 2,
  BYSUPPORUSER = 3,
  PHARMACYA_AFTERSEND = 4
}
