export interface EmploymentApplicationInterface {
    id: number;
    name: string;
    family: string;
    mobile: string;
    // email: string;
    nationalCode: string;
    birthDate: string;
    // pictureFileKey: string;
    gender: number;
    maritalStatus: number;
    hasReadingPrescriptionCertificate: true;
    gradeOfReadingPrescriptionCertificate: number;
    workExperienceYear: number;
    suggestedWorkShift: number;
    pharmaceuticalSoftwareSkill: number;
    computerSkill: number;
    foreignLanguagesSkill: number;
    countryDivisionCode: string;
    hasGuarantee: true;
    suggestedJobPosition: number;
    education: number;
    address: string;
    landlinePhone: string;
    previousWorkplace: string;
    previousWorkplacePhone: string;
    descriptions: string;
    resumeFileKey: string;
    readingPrescriptionCertificateStr: string;
    hasGuaranteeStr: string;
    genderStr: string;
    suggestedWorkShiftStr: string;
    maritalStatusStr: string;
    pharmaceuticalSoftwareSkillStr: string;
    computerSkillStr: string;
    foreignLanguagesSkillStr: string;
    suggestedJobPositionStr: string;
    educationStr: string;
    sendDate: string;
    cancelDate: string;
}
